/*
 * Framework100500
 * Copyright (c) 2019 Oleksandr Bondarenko
 * MIT Licensed
 */

const {
  KOA_HELMET_CONFIG,
  KOA_BODY_PARSER_CONFIG,
  KOA_COMPRESS_CONFIG,
  KOA_CORS_CONFIG,
  KOA_FAVICON_CONFIG,
  KOA_HEALTH_CONFIG,
  KOA_LOGGER_CONFIG,
  KOA_SERVE_STATIC_CONFIG,

  platform100500Koa,
} = require('./src');

module.exports = {
  KOA_HELMET_CONFIG,
  KOA_BODY_PARSER_CONFIG,
  KOA_COMPRESS_CONFIG,
  KOA_CORS_CONFIG,
  KOA_FAVICON_CONFIG,
  KOA_HEALTH_CONFIG,
  KOA_LOGGER_CONFIG,
  KOA_SERVE_STATIC_CONFIG,

  platform100500Koa,
};
