/*
 * Mind.js
 * Copyright (c) 2019 Oleksandr Bondarenko
 * MIT Licensed
 */

const {
  APP_ROUTER_PROVIDER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTER_MIDDLEWARE_INITIALIZER,
  APP_ROUTERS_INITIALIZER,
  APP_ROUTE_MOUNTER,

  RoutingModule,
} = require('./src');

module.exports = {
  APP_ROUTER_PROVIDER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTER_MIDDLEWARE_INITIALIZER,
  APP_ROUTERS_INITIALIZER,
  APP_ROUTE_MOUNTER,

  RoutingModule,
};
