const Framework100500 = require('./core');

const {
  Inject,
  Module,
  InjectableClass,
} = require('./decorators');

const {
  APP_INITIALIZER,
  APP_INJECTOR,
  APP_MIDDLEWARE,
  APP_MIDDLEWARE_INITIALIZER,
  APP_SERVER,
  APP_SERVER_ERROR_LISTENER,
  APP_SERVER_NET_LISTENER,
  MODULE_INJECTOR,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTERS,
  APP_ROUTERS_INITIALIZER,
  APP_ROUTER_PROVIDER,
} = require('./DI.tokens');

module.exports = {
  APP_INITIALIZER,
  APP_INJECTOR,
  APP_MIDDLEWARE,
  APP_MIDDLEWARE_INITIALIZER,
  APP_SERVER,
  APP_SERVER_ERROR_LISTENER,
  APP_SERVER_NET_LISTENER,
  MODULE_INJECTOR,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTER_PROVIDER,
  APP_ROUTERS,
  APP_ROUTERS_INITIALIZER,

  Inject,
  Module,
  InjectableClass,

  Framework100500,
};
