/*
 * Framework100500
 * Copyright (c) 2019 Oleksandr Bondarenko
 * MIT Licensed
 */

const {
  APP_INITIALIZER,
  APP_MIDDLEWARE,
  APP_MIDDLEWARE_INITIALIZER,
  APP_SERVER,
  APP_SERVER_ERROR_LISTENER,
  APP_SERVER_NET_LISTENER,
  APP_ROUTER_PROVIDER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTERS,
  APP_ROUTERS_INITIALIZER,

  Injectable,
  Inject,
  Module,

  Framework100500,
} = require('./src');

module.exports = {
  APP_INITIALIZER,
  APP_MIDDLEWARE,
  APP_MIDDLEWARE_INITIALIZER,
  APP_SERVER,
  APP_SERVER_ERROR_LISTENER,
  APP_SERVER_NET_LISTENER,
  APP_ROUTER_PROVIDER,
  APP_ROUTING_MODULES_RESOLVER,
  APP_ROUTER_DESCRIPTOR_RESOLVER,
  APP_ROUTERS,
  APP_ROUTERS_INITIALIZER,

  Inject,
  Module,
  Injectable,

  Framework100500,
};
